# Generated by Django 5.1.3 on 2024-11-24 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrarUsuarios', '0002_registeruser_delete_registerusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
