# Generated by Django 5.1.3 on 2024-11-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='feed',
            name='feed_unico_usuario_postagem',
        ),
        migrations.RemoveIndex(
            model_name='feed',
            name='Feed_feed_usuario_d5ce1a_idx',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='favorita',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='visualizada',
        ),
    ]
